//! One task in MCF's own task system.
//!
//! This is **layer 2** of the two-layer split in
//! docs/research/mcf-task-system-design.md: the players' *plan*, authored at
//! runtime by a commander or squad leader. Layer 1 -- what the mission maker
//! placed, and the intel it produces -- stays where it is, in objectives and
//! triggers. A task is not mission content; it is a decision about mission
//! content.
//!
//! The fields follow **SMEAC**, the five-paragraph operations order every
//! milsim unit already writes and reads (Situation, Mission, Execution,
//! Admin/Logistics, Command/Signal). That is deliberate: unit leaders are
//! trained in this format, so structuring a task this way asks them for
//! something they already know how to produce. A free-text box would throw
//! that structure away. See the UNITAF research in the design note.
//!
//! Every field is optional except an id and a title. A squad leader firing off
//! a quick retasking mid-contact should not have to fill in five paragraphs;
//! the structure is there when it helps, not as a gate.
//!
//! A task serialises itself (Serialize/Deserialize below) and both the
//! persistent store and the network layer use that one implementation. Two
//! formats for the same object would drift apart eventually, and the bug that
//! causes is miserable to find.

//! WARNING: these values are persisted as integers and survive server
//! restarts, so **append only, never reorder or remove**. Inserting a value in
//! the middle silently changes the meaning of every task already on disk --
//! which happened once during development: a stored ASSIGNED task came back as
//! PUBLISHED after a value was inserted above it. Nothing errors; the data
//! just quietly means something else.
enum MCF_ETaskState
{
	//! Being written. Nobody but the author can see it.
	DRAFT,
	//! On the board: published to the force, not yet delegated to anyone.
	//! A real and common state -- a commander posts a task before anyone has
	//! picked it up -- and the reason the model needs more than "assigned or
	//! not".
	PUBLISHED,
	ASSIGNED,
	ACKNOWLEDGED,
	COMPLETE,
	FAILED,
	CANCELLED
}

//! Who a task is assigned to. Mirrors the audience model deliberately -- the
//! command hierarchy is the same structure in both cases.
//!
//! Persisted as an integer: append only, never reorder. See the warning on
//! MCF_ETaskState.
enum MCF_ETaskAssignee
{
	NOBODY,
	PLAYER,
	GROUP,
	FACTION
}

class MCF_Task
{
	//! Field separator. A tab keeps a whole task on one line, which the
	//! line-based persistent store requires and which makes it a single RPC
	//! argument. Tabs and newlines inside values are escaped.
	protected static const string FIELD_SEP = "\t";
	protected static const string TAB_ESCAPE = "<t>";
	protected static const string NEWLINE_ESCAPE = "<n>";

	//! Unique within a mission. Generated by the store, not by the author.
	string m_sId;

	//! Short name, the one line that appears in a list.
	string m_sTitle;

	// --- SMEAC ---

	//! Situation: what is known, friendly and enemy.
	string m_sSituation;
	//! Mission: who does what, when, where, and why.
	string m_sMission;
	//! Execution: intent and scheme of manoeuvre.
	string m_sExecution;
	//! Administration and logistics: medical, resupply, casualty evacuation.
	string m_sAdminLogistics;
	//! Command and signal: comms plan and contingencies.
	string m_sCommandSignal;

	// --- Who ---

	//! Player id of whoever authored it.
	int m_iAuthorPlayerId;
	//! What kind of thing m_sAssigneeId refers to.
	MCF_ETaskAssignee m_eAssigneeType;
	//! Player id, group id or faction key, depending on m_eAssigneeType.
	string m_sAssigneeId;

	// --- State ---

	MCF_ETaskState m_eState;

	//! The subordinate's stated plan, briefed back up to confirm they
	//! understood. Real units do this ("back brief") and the design note
	//! calls it out as something a top-down-only model would miss.
	string m_sBackBrief;

	//! Event name, if any, whose firing completes this task -- the bridge back
	//! to layer 1, so a commander's plan can be tied to something the mission
	//! itself detects.
	string m_sCompleteEvent;

	void MCF_Task()
	{
		m_eState = MCF_ETaskState.DRAFT;
		m_eAssigneeType = MCF_ETaskAssignee.NOBODY;
	}

	//! A reference a person can say out loud on the net: "OPORD-003".
	//!
	//! Real units number their orders and refer to them by that number, not by
	//! their subject line. Derived from the id rather than stored, so there is
	//! still exactly one identity per task and nothing to keep in sync.
	string GetReference()
	{
		string digits = m_sId;
		digits.Replace("t", "");

		int number = digits.ToInt();
		if (number <= 0)
			return "OPORD-" + m_sId;

		string padded = number.ToString();
		while (padded.Length() < 3)
			padded = "0" + padded;

		return "OPORD-" + padded;
	}

	//! How a state is written on the board.
	//!
	//! The enum names are engineering words; these are the words a unit would
	//! actually use. PUBLISHED in particular reads wrong to a soldier -- what
	//! it means is that the order is on the board and nobody has picked it up,
	//! so it is shown as OPEN.
	static string StateLabel(MCF_ETaskState state)
	{
		switch (state)
		{
			case MCF_ETaskState.DRAFT:        return "DRAFT";
			case MCF_ETaskState.PUBLISHED:    return "OPEN";
			case MCF_ETaskState.ASSIGNED:     return "TASKED";
			case MCF_ETaskState.ACKNOWLEDGED: return "ACKNOWLEDGED";
			case MCF_ETaskState.COMPLETE:     return "COMPLETE";
			case MCF_ETaskState.FAILED:       return "FAILED";
			case MCF_ETaskState.CANCELLED:    return "CANCELLED";
		}

		return "UNKNOWN";
	}


	//! One-line summary for logs and lists.
	string Describe()
	{
		return "[" + m_sId + "] \"" + m_sTitle + "\" " + typename.EnumToString(MCF_ETaskState, m_eState) + " -> " + typename.EnumToString(MCF_ETaskAssignee, m_eAssigneeType) + " " + m_sAssigneeId;
	}

	//! Everything about this task on one line. Used by both the persistent
	//! store and the network layer.
	string Serialize()
	{
		array<string> parts = {};
		parts.Insert("id=" + Escape(m_sId));
		parts.Insert("title=" + Escape(m_sTitle));
		parts.Insert("situation=" + Escape(m_sSituation));
		parts.Insert("mission=" + Escape(m_sMission));
		parts.Insert("execution=" + Escape(m_sExecution));
		parts.Insert("adminLog=" + Escape(m_sAdminLogistics));
		parts.Insert("cmdSignal=" + Escape(m_sCommandSignal));
		parts.Insert("backBrief=" + Escape(m_sBackBrief));
		parts.Insert("author=" + m_iAuthorPlayerId.ToString());
		parts.Insert("assigneeType=" + m_eAssigneeType.ToString());
		parts.Insert("assigneeId=" + Escape(m_sAssigneeId));
		parts.Insert("state=" + m_eState.ToString());
		parts.Insert("completeEvent=" + Escape(m_sCompleteEvent));

		string result = "";
		foreach (int i, string part : parts)
		{
			if (i > 0)
				result = result + FIELD_SEP;
			result = result + part;
		}
		return result;
	}

	//! Rebuilds a task from Serialize() output.
	//! \return The task, or null if the data is unusable.
	static MCF_Task Deserialize(string data)
	{
		if (data.IsEmpty())
			return null;

		array<string> parts = {};
		data.Split(FIELD_SEP, parts, false);

		MCF_Task task = new MCF_Task();

		foreach (string part : parts)
		{
			int split = part.IndexOf("=");
			if (split <= 0)
				continue;

			string key = part.Substring(0, split);
			string value = part.Substring(split + 1, part.Length() - split - 1);

			switch (key)
			{
				case "id":            task.m_sId = Unescape(value); break;
				case "title":         task.m_sTitle = Unescape(value); break;
				case "situation":     task.m_sSituation = Unescape(value); break;
				case "mission":       task.m_sMission = Unescape(value); break;
				case "execution":     task.m_sExecution = Unescape(value); break;
				case "adminLog":      task.m_sAdminLogistics = Unescape(value); break;
				case "cmdSignal":     task.m_sCommandSignal = Unescape(value); break;
				case "backBrief":     task.m_sBackBrief = Unescape(value); break;
				case "author":        task.m_iAuthorPlayerId = value.ToInt(); break;
				case "assigneeType":  task.m_eAssigneeType = value.ToInt(); break;
				case "assigneeId":    task.m_sAssigneeId = Unescape(value); break;
				case "state":         task.m_eState = value.ToInt(); break;
				case "completeEvent": task.m_sCompleteEvent = Unescape(value); break;
			}
		}

		if (task.m_sId.IsEmpty())
			return null;

		return task;
	}

	protected static string Escape(string value)
	{
		if (value.IsEmpty())
			return value;

		string result = value;
		result.Replace(FIELD_SEP, TAB_ESCAPE);
		result.Replace("\n", NEWLINE_ESCAPE);
		result.Replace("\r", "");
		return result;
	}

	protected static string Unescape(string value)
	{
		if (value.IsEmpty())
			return value;

		string result = value;
		result.Replace(TAB_ESCAPE, FIELD_SEP);
		result.Replace(NEWLINE_ESCAPE, "\n");
		return result;
	}
}
