SCR_MissionHeader {
 World "{C68D029B6BA62525}worlds/arland/MCFTestworld.ent"
 SystemsConfig "{8DDC2A311929D52F}Configs/Systems/GameMasterSystems.conf"
 m_sName "MCF test world"
 m_sAuthor "Olmo"
 m_sDescription "A world to test out basic MCF functions"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
}