SCR_PlaceableEntitiesRegistry {
 m_sAddon "MCF"
 m_bExposed 1
 m_Prefabs {
  "Prefabs/MCF_AI_LifestylePOI.et"
  "Prefabs/MCF_AI_SafeFallbackPoint.et"
  "Prefabs/MCF_Obj_AlarmTrigger.et"
  "Prefabs/MCF_Obj_ConeDetectionTrigger.et"
  "Prefabs/MCF_Obj_Logic.et"
  "Prefabs/MCF_Obj_Objective.et"
  "Prefabs/MCF_Obj_Observation.et"
  "Prefabs/MCF_Obj_ProximityTrigger.et"
  "Prefabs/MCF_Obj_SpottedByPlayer.et"
  "Prefabs/MCF_Obj_TriggerZone.et"
  "Prefabs/MCF_React_Recipe.et"
  "Prefabs/MCF_Voice_TextLine.et"
 }
}
