SCR_PlaceableEntitiesRegistry {
 m_sAddon "MCF"
 m_Prefabs {
  "{184E53E0A8432492}Prefabs/MCF_AI_LifestylePOI.et"
  "{BFC49769076A5E8F}Prefabs/MCF_AI_SafeFallbackPoint.et"
  "{7C1C7AF3B7A5E235}Prefabs/MCF_Obj_AlarmTrigger.et"
  "{39587CB7990142DB}Prefabs/MCF_Obj_ConeDetectionTrigger.et"
  "{4BA5C8B66230AD7E}Prefabs/MCF_Obj_Logic.et"
  "{4140EC81C688E72A}Prefabs/MCF_Obj_Objective.et"
  "{70DB9AFBB9CEC678}Prefabs/MCF_Obj_Observation.et"
  "{93DD018EA883606C}Prefabs/MCF_Obj_ProximityTrigger.et"
  "{32F3B4409A17CCFD}Prefabs/MCF_Obj_SpottedByPlayer.et"
  "{D3F53DABF6767388}Prefabs/MCF_Obj_TriggerZone.et"
  "{7D434245D3D440FD}Prefabs/MCF_React_Recipe.et"
  "{568DFDB7F360AB62}Prefabs/MCF_Voice_TextLine.et"
 }
}