SCR_PlaceableEntitiesRegistry {
 m_sAddon "MCF"
 m_sSourceDirectory ""
 m_bExposed 1
 m_Prefabs {
  "{927A8ABC1DDA257C}Prefabs/MCF_AI_LifestylePOI.et"
  "{3C54A0573FF746FA}Prefabs/MCF_AI_SafeFallbackPoint.et"
  "{E58D985218B33D3A}Prefabs/MCF_Obj_AlarmTrigger.et"
  "{2D283A489D1D8BCC}Prefabs/MCF_Obj_ConeDetectionTrigger.et"
  "{C50C4BFCD3BB354F}Prefabs/MCF_Obj_Logic.et"
  "{EE2F97C40CD99F15}Prefabs/MCF_Obj_Objective.et"
  "{B5F266B9FD4501CE}Prefabs/MCF_Obj_Observation.et"
  "{8A24F93EA862750C}Prefabs/MCF_Obj_ProximityTrigger.et"
  "{6C5FE2CCB6B45596}Prefabs/MCF_Obj_SpottedByPlayer.et"
  "{39A7C5F59B6CF78B}Prefabs/MCF_Obj_TriggerZone.et"
  "{77EA9923B4F69728}Prefabs/MCF_React_Recipe.et"
  "{6A1C4F0B39D2D010}Prefabs/MCF_Intel_Letter.et"
  "{6A1C4F0B39D2D020}Prefabs/MCF_Intel_Notebook.et"
  "{6A1C4F0B39D2D030}Prefabs/MCF_Intel_Source.et"
  "{6A1C4F0B39D2D060}Prefabs/MCF_Intel_Laptop.et"
  "{6A1C4F0B39E12000}Prefabs/MCF_Map_Board.et"
  "{6A1C4F0B39D2D040}Prefabs/MCF_Dialogue_Assign.et"
  "{6A1C4F0B39D27E10}Prefabs/MCF_Task_Board.et"
  "{152F65EF13B76096}Prefabs/MCF_Voice_TextLine.et"
  "{6A1C4F0B39D30100}Prefabs/MCF_Devices_Phone.et"
 }
}