ActionManager {
 Contexts +{
  ActionContext MCF_CharacterContext {
   Priority 10
   Flags 0x2 0
   Actions {
    Action MCF_ShoutSurrender {
     InputSource InputSourceSum "{6A1C4F0B39D2B200}" {
      Sources {
       InputSourceValue "{6A1C4F0B39D2B201}" {
        FilterPreset "click"
        Input "keyboard:KC_H"
        Filter InputFilterClick "{6A1C4F0B39D2B202}" {
        }
       }
      }
     }
    }
    Action MCF_ShoutStayBack {
     InputSource InputSourceSum "{6A1C4F0B39D2B203}" {
      Sources {
       InputSourceValue "{6A1C4F0B39D2B204}" {
        FilterPreset "click"
        Input "keyboard:KC_U"
        Filter InputFilterClick "{6A1C4F0B39D2B205}" {
        }
       }
      }
     }
    }
   }
  }
 }
}
