SCR_EntityCatalog {
 m_sCategoryName "MCF Framework"
 m_aEntries {
  SCR_EntityCatalogEntry {
   m_sPrefab "{39A7C5F59B6CF78B}Prefabs/MCF_Obj_TriggerZone.et"
  }
  SCR_EntityCatalogEntry {
   m_sPrefab "{EE2F97C40CD99F15}Prefabs/MCF_Obj_Objective.et"
  }
  SCR_EntityCatalogEntry {
   m_sPrefab "{C50C4BFCD3BB354F}Prefabs/MCF_Obj_Logic.et"
  }
  SCR_EntityCatalogEntry {
   m_sPrefab "{B5F266B9FD4501CE}Prefabs/MCF_Obj_Observation.et"
  }
  SCR_EntityCatalogEntry {
   m_sPrefab "{8A24F93EA862750C}Prefabs/MCF_Obj_ProximityTrigger.et"
  }
  SCR_EntityCatalogEntry {
   m_sPrefab "{2D283A489D1D8BCC}Prefabs/MCF_Obj_ConeDetectionTrigger.et"
  }
  SCR_EntityCatalogEntry {
   m_sPrefab "{E58D985218B33D3A}Prefabs/MCF_Obj_AlarmTrigger.et"
  }
  SCR_EntityCatalogEntry {
   m_sPrefab "{6C5FE2CCB6B45596}Prefabs/MCF_Obj_SpottedByPlayer.et"
  }
  SCR_EntityCatalogEntry {
   m_sPrefab "{77EA9923B4F69728}Prefabs/MCF_React_Recipe.et"
  }
  SCR_EntityCatalogEntry {
   m_sPrefab "{927A8ABC1DDA257C}Prefabs/MCF_AI_LifestylePOI.et"
  }
  SCR_EntityCatalogEntry {
   m_sPrefab "{3C54A0573FF746FA}Prefabs/MCF_AI_SafeFallbackPoint.et"
  }
  SCR_EntityCatalogEntry {
   m_sPrefab "{152F65EF13B76096}Prefabs/MCF_Voice_TextLine.et"
  }
 }
}
