//! One piece of intel that has been logged to the operations board.
//!
//! The difference between this and MCF_Intel_Entry matters. An entry is what
//! an object *says* -- it sits in a prefab, it is read where it lies, and it
//! is known only to whoever picked the thing up. A record is what the force
//! *knows*: somebody carried that object to a commander, the commander entered
//! it, and from that moment it is shared, persisted and usable as the basis
//! for an order.
//!
//! Keeping them as two types is the whole point of the design. Collapsing them
//! into one would mean intel is known the instant it exists, and the carrying
//! -- which is the interesting part -- would stop mattering.
//!
//! Serialises itself the same way MCF_Task does, and for the same reason: the
//! persistent store and the network layer share one implementation so the two
//! cannot drift apart.

class MCF_Intel_Record
{
	protected static const string FIELD_SEP = "\t";
	protected static const string TAB_ESCAPE = "<t>";
	protected static const string NEWLINE_ESCAPE = "<n>";

	//! Unique within a mission. Generated by the store.
	string m_sId;

	//! What it came off -- "Handwritten letter", "Field notebook". Provenance
	//! is half of what makes intel judgeable: a scrap off a body reads
	//! differently from a signed order.
	string m_sSource;

	//! Short subject line.
	string m_sHeading;

	//! When the source said it happened. Free text, as authored.
	string m_sTimestamp;

	//! The content itself.
	string m_sBody;

	//! Who entered it into the system.
	int m_iLoggedByPlayerId;

	//! The faction that holds this intel -- the faction of whoever logged it,
	//! captured at the moment of logging rather than looked up later, because
	//! a player who switches sides must not drag the report across with them.
	//!
	//! EMPTY MEANS EVERYONE. Records written before this field existed have no
	//! faction and stay visible to all, which is the right answer for old data:
	//! silently hiding intel a mission already had would look like data loss.
	string m_sFactionKey;

	//! The address of a photograph that belongs with this report, if there is
	//! one. The ADDRESS, not the picture: a texture cannot travel over an RPC
	//! and would not be worth persisting if it could, because every machine that
	//! displays it fetches and caches its own copy already.
	//!
	//! Empty on every record written before pictures existed, which is exactly
	//! what a report without one looks like anyway.
	string m_sImageUrl;

	//! One-line summary for logs and lists.
	string Describe()
	{
		return "[" + m_sId + "] " + m_sHeading + " (" + m_sSource + ")";
	}

	//! A reference a person can say on the net.
	string GetReference()
	{
		string digits = m_sId;
		digits.Replace("i", "");

		int number = digits.ToInt();
		if (number <= 0)
			return "INTREP-" + m_sId;

		string padded = number.ToString();
		while (padded.Length() < 3)
			padded = "0" + padded;

		return "INTREP-" + padded;
	}

	string Serialize()
	{
		array<string> parts = {};
		parts.Insert("id=" + Escape(m_sId));
		parts.Insert("source=" + Escape(m_sSource));
		parts.Insert("heading=" + Escape(m_sHeading));
		parts.Insert("stamp=" + Escape(m_sTimestamp));
		parts.Insert("body=" + Escape(m_sBody));
		parts.Insert("by=" + m_iLoggedByPlayerId.ToString());
		parts.Insert("faction=" + Escape(m_sFactionKey));
		parts.Insert("image=" + Escape(m_sImageUrl));

		string result = "";
		foreach (int i, string part : parts)
		{
			if (i > 0)
				result = result + FIELD_SEP;
			result = result + part;
		}
		return result;
	}

	static MCF_Intel_Record Deserialize(string data)
	{
		if (data.IsEmpty())
			return null;

		array<string> parts = {};
		data.Split(FIELD_SEP, parts, false);

		MCF_Intel_Record record = new MCF_Intel_Record();

		foreach (string part : parts)
		{
			int split = part.IndexOf("=");
			if (split <= 0)
				continue;

			string key = part.Substring(0, split);
			string value = part.Substring(split + 1, part.Length() - split - 1);

			switch (key)
			{
				case "id":      record.m_sId = Unescape(value); break;
				case "source":  record.m_sSource = Unescape(value); break;
				case "heading": record.m_sHeading = Unescape(value); break;
				case "stamp":   record.m_sTimestamp = Unescape(value); break;
				case "body":    record.m_sBody = Unescape(value); break;
				case "by":      record.m_iLoggedByPlayerId = value.ToInt(); break;
				case "faction": record.m_sFactionKey = Unescape(value); break;
				case "image":   record.m_sImageUrl = Unescape(value); break;
			}
		}

		if (record.m_sId.IsEmpty())
			return null;

		return record;
	}

	protected static string Escape(string value)
	{
		if (value.IsEmpty())
			return value;

		string result = value;
		result.Replace(FIELD_SEP, TAB_ESCAPE);
		result.Replace("\n", NEWLINE_ESCAPE);
		result.Replace("\r", "");
		return result;
	}

	protected static string Unescape(string value)
	{
		if (value.IsEmpty())
			return value;

		string result = value;
		result.Replace(TAB_ESCAPE, FIELD_SEP);
		result.Replace(NEWLINE_ESCAPE, "\n");
		return result;
	}
}
