MenuManager {
 MenuPresets +{
  MenuPreset MCF_PlanningBoard {
   Layout "{6A1C4F0B39D2A100}UI/layouts/MCF/MCF_PlanningBoard.layout"
   ActionContext "MenuContext"
   Class "MCF_PlanningBoardMenu"
  }
  MenuPreset MCF_IntelViewer {
   Layout "{6A1C4F0B39D2C000}UI/layouts/MCF/MCF_IntelViewer.layout"
   ActionContext "MenuContext"
   Class "MCF_Intel_ViewerMenu"
  }
  MenuPreset MCF_IntelEditor {
   Layout "{6A1C4F0B39D2E000}UI/layouts/MCF/MCF_IntelEditor.layout"
   ActionContext "EditorAttributeDialogContext"
   Class "MCF_Intel_EditorMenu"
  }
  MenuPreset MCF_IntelPaper {
   Layout "{6A1C4F0B39D32000}UI/layouts/MCF/MCF_IntelPaper.layout"
   ActionContext "MenuContext"
   Class "MCF_Intel_ShellMenu"
  }
  MenuPreset MCF_IntelNotepad {
   Layout "{6A1C4F0B39D33000}UI/layouts/MCF/MCF_IntelNotepad.layout"
   ActionContext "MenuContext"
   Class "MCF_Intel_ShellMenu"
  }
  MenuPreset MCF_IntelDevice {
   Layout "{6A1C4F0B39D31000}UI/layouts/MCF/MCF_IntelDevice.layout"
   ActionContext "MenuContext"
   Class "MCF_Intel_ShellMenu"
  }
  MenuPreset MCF_Dialogue {
   Layout "{6A1C4F0B39D2F000}UI/layouts/MCF/MCF_Dialogue.layout"
   ActionContext "MenuContext"
   Class "MCF_Dialogue_Menu"
  }
  MenuPreset MCF_DialogueEditor {
   Layout "{6A1C4F0B39D2F100}UI/layouts/MCF/MCF_DialogueEditor.layout"
   ActionContext "EditorAttributeDialogContext"
   Class "MCF_Dialogue_EditorMenu"
  }
  MenuPreset MCF_DeviceEditor {
   Layout "{6A1C4F0B39D34800}UI/layouts/MCF/MCF_DeviceEditor.layout"
   ActionContext "EditorAttributeDialogContext"
   Class "MCF_Device_EditorMenu"
  }
  MenuPreset MCF_DataManager {
   Layout "{6A1C4F0B39D36000}UI/layouts/MCF/MCF_DataManager.layout"
   Class "MCF_Data_ManagerMenu"
  }
  MenuPreset MCF_DeviceHack {
   Layout "{6A1C4F0B39D30000}UI/layouts/MCF/MCF_DeviceHack.layout"
   ActionContext "MenuContext"
   Class "MCF_Devices_HackMenu"
  }
 }
}
