SCR_MissionHeader {
 World "{C68D029B6BA62525}worlds/arland/MCFTestworld.ent"
 m_sName "<Insert world name>"
 m_sAuthor "<Insert your name>"
 m_sDescription "<Insert world description>"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
}